# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PerlIO-via-Logger
version:      0.02
version_from: lib/PerlIO/via/Logger.pm
installdirs:  site
requires:
    POSIX:                         0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
